#!/usr/bin/env bash

# AUTOCOMPLETION FOR BASH
# Reference: https://www.gnu.org/software/bash/manual/html_node/A-Programmable-Completion-Example.html

_wt() {
    local cur
	# The currently typed prefix to be completed
	cur="${COMP_WORDS[COMP_CWORD]}"
	COMPREPLY=()

    # Only show suggestions for the root command (wt)
    # Pass autocompletion suggestion as "words (-W)" to `compgen` separated by space
	# Escape each suggestion special characters
    if [[ ${cur} == -* || ${COMP_CWORD} -eq 1 ]]; then
		# Use the newline as a separator for the suggestions
		local IFS=$'\n'
		local suggestions
		suggestions=$(compgen -W "$(wt names)" -- "$cur")
		for word in $suggestions; do
			COMPREPLY+=("$(printf '%q' "$word")")
		done
    fi
}

# complete
#   -F: take function as completion provider
#   _wt: name of the function
#   wt: name of the command this completion is meant for
complete -F _wt wt
